const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  setFileAssociations: (browser) => ipcRenderer.invoke('set-file-associations', browser),
  getCurrentAssociations: () => ipcRenderer.invoke('get-current-associations'),
  openBrowserSettings: (browser) => ipcRenderer.invoke('open-browser-settings', browser),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  getPlatform: () => ipcRenderer.invoke('get-platform'),
  getBluetoothDevices: () => ipcRenderer.invoke('get-bluetooth-devices'),
  showNotification: (title, body) => ipcRenderer.invoke('show-notification', title, body),
  emptyRecycleBin: () => ipcRenderer.invoke('empty-recycle-bin'),
  openAppData: () => ipcRenderer.invoke('open-appdata'),
  transferStart: () => ipcRenderer.invoke('transfer-start'),
  transferStop: () => ipcRenderer.invoke('transfer-stop'),
  transferAddShared: () => ipcRenderer.invoke('transfer-add-shared'),
  transferSharePaths: (paths) => ipcRenderer.invoke('transfer-share-paths', paths),
  transferSendText: (text) => ipcRenderer.invoke('transfer-send-text', text),
  transferPcMessages: () => ipcRenderer.invoke('transfer-pc-messages'),
  getPathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return ''; } },
  transferRemoveShared: (id) => ipcRenderer.invoke('transfer-remove-shared', id),
  transferGetShared: () => ipcRenderer.invoke('transfer-get-shared'),
  transferReceived: () => ipcRenderer.invoke('transfer-received'),
  transferClearReceived: () => ipcRenderer.invoke('transfer-clear-received'),
  transferStatus: () => ipcRenderer.invoke('transfer-status'),
  transferOpenFolder: () => ipcRenderer.invoke('transfer-open-folder'),
  getMundialScores: () => ipcRenderer.invoke('get-mundial-scores'),
  getMundialArgentina: () => ipcRenderer.invoke('get-mundial-argentina'),
  getCryptoPrices: () => ipcRenderer.invoke('get-crypto-prices'),
  getCryptoChart: (coinId, days) => ipcRenderer.invoke('get-crypto-chart', coinId, days),
  getDolarBlue: () => ipcRenderer.invoke('get-dolar-blue'),
  isDesktop: true,
});
